language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  - docker build -t vc/node -f Dockerfile.dev . 
  - docker pull mongo 
before_script:
  - docker-compose up -d --build
script:
  - docker run vc/node npm test -- --coverage
