language: node_js
node_js:
  - "8"
services:
  - docker
  - mongodb
before_install:
  - docker build -t vc/node -f Dockerfile.dev . 
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - docker run vc/node npm test -- --coverage
