language: generic
sudo : required
services:
  - docker
  - mongodb
env: 
  MONGODB_URL: "mongodb://127.0.0.1:27017/trucks-db-test"
  PORT: "5000"
  JWT_SECRET: "clientsecretToChange"
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
before_install:
  - docker build -t vc/node -f Dockerfile.test . 
script:
  - mongod docker run vc/node npm run test-travis -- --coverage
