language: generic
sudo : required
services:
  - docker
  - mongodb
env: 
  MONGODB_URL: "mongodb://localhost:27017/trucks-db-test"
  PORT: "5000"
  JWT_SECRET: "clientsecretToChange"
before_install:
  - docker build -t vc/node -f Dockerfile.test . 
script:
  - docker run vc/node npm run test-travis -- --coverage
