language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  - docker build -t vc/node -f Dockerfile.dev 
script:
  - docker run vc/node npm test -- --coverage
deploy:
	provider: elasticbeanstalk
	region: "us-east-1"
	app: "Docker-Node-Trucks"
	env: "DockerNodeTrucks-env"
	bucket_name: "elasticbeanstalk-us-east-1-424043981863"
	bucket_path: "Docker-Node-Trucks"
	on:
		branch: master	
	access_key_id: $AWS_ACCESS_KEY
	secret_access_key: 
		secure: $AWS_SECRET_KEY
