language: generic
sudo: required
services: 
  - docker
  - mongodb

before_install: 
  - docker build -t vc/docker-node -f Dockerfile.dev . 

script: 
  - docker run -e CI=true vc/docker-node npm run test-travis -- --coverage


