language: node_js
sudo : required
node_js:
  - "8"
services:
  - docker
  - mongodb
env: 
  MONGODB_URL: "mongodb://localhost:27017/trucks-db"
  PORT: "5000"
  JWT_SECRET: "JWT_SECRET"
before_install:
  - docker build -t vc/node -f Dockerfile.test . 
script:
  - docker run vc/node npm run test-travis -- --coverage
