language: node_js
node_js:
  - "8"
dist: trusty
services:
  - docker
  - mongodb
env:
  - NODE_ENV=ci
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
deploy:
	provider: elasticbeanstalk
	region: "us-east-1"
	app: "Docker-Node-Trucks"
	env: "DockerNodeTrucks-env"
	bucket_name: "elasticbeanstalk-us-east-1-424043981863"
	bucket_path: "Docker-Node-Trucks"
	on:
		branch: master	
	access_key_id: $AWS_ACCESS_KEY
	secret_access_key: 
		secure: $AWS_SECRET_KEY
