language: node_js
sudo : required
node_js:
  - "8"
services:
  - docker
  - mongodb
env: 
  MONGODB_URL: $MONGODB_URL
  PORT: $PORT
  JWT_SECRET: $JWT_SECRET
before_install:
  - docker build -t vc/node -f Dockerfile.dev . 
script:
  - docker run vc/node npm run start -- --coverage
