version: '3'
services:
  web:
    image: "node-docker-truck-app"
    build:
      dockerfile: Dockerfile.test
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
