version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    depends_on:
      - api
      - client
    restart: always    
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4050:80'
  api:
    depends_on: 
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  client:
    stdin_open: true
    build:  
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
      