version: '3'
services:
  web:
    image: "node-docker-truck-app"
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongo:27017/trucks-db
      - JWT_SECRET=clientsecretToChange
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
